### ISSUE TITLE
Question - Running Dagger in my Gitlab CI

### ISSUE THREAD

**Issue by cavo789** [google/dagger#4522]
Hi all

I'm trying to run my Dagger pipeline in a GitLab CI and I get an error while connecting to the Dagger engine.

Here my `.gitlab-ci.yml` file (almost the same than [https://docs.dagger.io/integrations/gitlab/#examples](https://docs.dagger.io/integrations/gitlab/#examples))

```yaml
.docker:
  image: docker:latest
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: false
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '27.3.1'
.dagger:
  extends: [.docker]
  before_script:
    - apk add curl
    - curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
lint:
  extends: [.dagger]
  script:
    - docker --version
    - docker info
    - dagger call --source src --config .config lint
```

And here the error

![Image](https://github.com/user-attachments/assets/458cf054-249b-4578-b154-583be91e3daa)

The command `docker --version` returns `Docker version 27.3.1, build ce12230`  and `docker info` is well giving me all the informations (so DIND is working I think).

Can someone help please?

Thanks!!!
